#include "+ A.h"




void + A::perimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--103-1-2c9bd139:16deeff2ef5:-8000:000000000000099C begin
{
}
// section -64--88--103-1-2c9bd139:16deeff2ef5:-8000:000000000000099C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void + A::+ aire()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--103-1-2c9bd139:16deeff2ef5:-8000:00000000000009A4 begin
{
}
// section -64--88--103-1-2c9bd139:16deeff2ef5:-8000:00000000000009A4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
