#include "adhérents.h"




void adhérents::emprunt_Livre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--103-1--9396a5f:16e1cf07d95:-8000:0000000000001A37 begin
{
}
// section -64--88--103-1--9396a5f:16e1cf07d95:-8000:0000000000001A37 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void adhérents::restituer_Livre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--103-1--9396a5f:16e1cf07d95:-8000:0000000000001A61 begin
{
}
// section -64--88--103-1--9396a5f:16e1cf07d95:-8000:0000000000001A61 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
