#include "bobliotheque.h"




void bobliotheque::inscrit_adherent()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--103-1--9396a5f:16e1cf07d95:-8000:0000000000001A47 begin
{
}
// section -64--88--103-1--9396a5f:16e1cf07d95:-8000:0000000000001A47 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void bobliotheque::desincrit_adherent()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--103-1--9396a5f:16e1cf07d95:-8000:0000000000001A64 begin
{
}
// section -64--88--103-1--9396a5f:16e1cf07d95:-8000:0000000000001A64 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void bobliotheque::ajouter_document()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--103-1--9396a5f:16e1cf07d95:-8000:0000000000001A66 begin
{
}
// section -64--88--103-1--9396a5f:16e1cf07d95:-8000:0000000000001A66 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
