#include "Livres.h"




void Livres::empruntable()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--103-1--9396a5f:16e1cf07d95:-8000:0000000000001A6C begin
{
}
// section -64--88--103-1--9396a5f:16e1cf07d95:-8000:0000000000001A6C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
